name: Commit policy
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Check messages
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@v1.1.0
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
